name: "ffuf-action"
description: "This action can help you to fuzz directories using github actions."
branding:
  icon: "activity"
  color: "blue"

inputs:

  wordlist:
    description: "Path to the wordlist file."
    required: true      

  config:
    description: "Path to the config file."
    required: true    

  output:
    description: "File to save output result"
    required: false
    default: "ffuf-result.html"     


runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/ffuf ] && go install github.com/ffuf/ffuf@latest
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        /home/runner/go/bin/ffuf -w=${{ inputs.wordlist }} -config=${{ inputs.config }} -o=${{ inputs.output }}      
      shell: bash